import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/Provider";
import { Container, Theme } from "@radix-ui/themes";
import QueryClientProvider from "./QueryClientProvider";
import Navbar from "./components/Navbar";
import { SearchContextProvider } from "./contexts/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="dark" accentColor="amber" grayColor="sage">
              <Container maxWidth="1000px">
                <SearchContextProvider>
                  <Navbar />
                  {children}
                </SearchContextProvider>
              </Container>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
